// THIS FILE IS AUTOGENERATED
// Do not directly modify this file. Instead, consider adding to 
// /script/native-modules.json or the /script/*.handlebars templates.
// 
// To regenerate these files run 'node build --gen'
//

#include "modules.h"

#include <sys/types.h>

#include "jerryscript.h"
#include "jerry_helper.h"
#include "callback_engine.h"

typedef uint64_t absolute_time_t;

static jerry_value_t sleep_until_handler(const jerry_value_t function_obj, const jerry_value_t this_val, const jerry_value_t args_p[], const jerry_length_t args_count)
{
    jerry_value_t ret_val;

    if (
        args_count != 1
        || !jerry_value_is_number(args_p[0])
    )
    {
        ret_val = psj_jerry_create_error_obj(RUNTIME_ARG_ERROR, "sleep_until(number)");
        goto cleanup;
    }

    absolute_time_t target = (absolute_time_t)psj_jerry_to_uint64_t(args_p[0]);

    jerry_port_log(JERRY_LOG_LEVEL_TRACE, "sleep_until(%i);", target);
    
    ret_val = jerry_create_undefined();

cleanup:

    return ret_val;
}

static jerry_value_t sleep_us_handler(const jerry_value_t function_obj, const jerry_value_t this_val, const jerry_value_t args_p[], const jerry_length_t args_count)
{
    jerry_value_t ret_val;

    if (
        args_count != 1
        || !jerry_value_is_number(args_p[0])
    )
    {
        ret_val = psj_jerry_create_error_obj(RUNTIME_ARG_ERROR, "sleep_us(number)");
        goto cleanup;
    }

    uint64_t us = psj_jerry_to_uint64_t(args_p[0]);

    jerry_port_log(JERRY_LOG_LEVEL_TRACE, "sleep_us(%i);", us);
    
    ret_val = jerry_create_undefined();

cleanup:

    return ret_val;
}

static jerry_value_t sleep_ms_handler(const jerry_value_t function_obj, const jerry_value_t this_val, const jerry_value_t args_p[], const jerry_length_t args_count)
{
    jerry_value_t ret_val;

    if (
        args_count != 1
        || !jerry_value_is_number(args_p[0])
    )
    {
        ret_val = psj_jerry_create_error_obj(RUNTIME_ARG_ERROR, "sleep_ms(number)");
        goto cleanup;
    }

    uint32_t ms = psj_jerry_to_uint32_t(args_p[0]);

    jerry_port_log(JERRY_LOG_LEVEL_TRACE, "sleep_ms(%i);", ms);
    
    ret_val = jerry_create_undefined();

cleanup:

    return ret_val;
}

static jerry_value_t best_effort_wfe_or_timeout_handler(const jerry_value_t function_obj, const jerry_value_t this_val, const jerry_value_t args_p[], const jerry_length_t args_count)
{
    jerry_value_t ret_val;

    if (
        args_count != 1
        || !jerry_value_is_number(args_p[0])
    )
    {
        ret_val = psj_jerry_create_error_obj(RUNTIME_ARG_ERROR, "best_effort_wfe_or_timeout(number)");
        goto cleanup;
    }

    absolute_time_t timeout_timestamp = (absolute_time_t)psj_jerry_to_uint64_t(args_p[0]);

    jerry_port_log(JERRY_LOG_LEVEL_TRACE, "best_effort_wfe_or_timeout(%i);", timeout_timestamp);
    const bool v = true;
    ret_val = jerry_create_boolean(v);

cleanup:

    return ret_val;
}

jerry_value_t get_highlevel_module()
{
    jerry_value_t module = jerry_create_object();
    jerry_value_t handler;

    handler = jerry_create_external_function(sleep_until_handler);
    psj_jerry_set_property(module, "sleep_until", handler);
    jerry_release_value(handler);

    handler = jerry_create_external_function(sleep_us_handler);
    psj_jerry_set_property(module, "sleep_us", handler);
    jerry_release_value(handler);

    handler = jerry_create_external_function(sleep_ms_handler);
    psj_jerry_set_property(module, "sleep_ms", handler);
    jerry_release_value(handler);

    handler = jerry_create_external_function(best_effort_wfe_or_timeout_handler);
    psj_jerry_set_property(module, "best_effort_wfe_or_timeout", handler);
    jerry_release_value(handler);

    return module;
}