# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  workflow_dispatch:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # PRODUCT_NAME is set in the 'Run build' step
  PRODUCT_NAME: tbd.0.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4.0.1

    - name: Pull NPM Packages
      run: npm install

    - name: Check for changefiles
      run: npm run beachball:check

    - name: pull submodules
      run: git submodules update --init --recursive

    - uses: ConorMacBride/install-package@v1
      name: Install APT packages
      with:
        apt: nodejs npm cmake gcc gcc-arm-none-eabi cppcheck clang-format libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Run build
      run: node build --rebuild --target rp2xxx --release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PRODUCT_NAME }}
        path: |
          build/pico-sdk-js-*.*
