name: Build RP2XXX Package

permissions: 
  contents: write

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Release'
        type: boolean
        default: false

  pull_request:
    branches: [ "main" ]

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:

      # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
  
      - name: Pull NPM Packages
        run: npm install
  
      - name: Check for changefiles
        run: npm run beachball:check
    
  build:
    runs-on: ubuntu-latest
    needs: [prebuild]
    if: ${{ ! ( github.event_name == 'pull_request' && contains( github.event.pull_request.title, '[NO_BUILD]' ) ) }}
    outputs:
      PRODUCT_NAME: ${{ steps.run-build.outputs.PRODUCT_NAME }}
      PACKAGE_NAME: ${{ steps.run-build.outputs.PACKAGE_NAME }}
      PACKAGE_VERSION: ${{ steps.run-build.outputs.PACKAGE_VERSION }}

    steps:

    # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: actions/setup-node@v4.0.1

    - name: Pull NPM Packages
      run: npm install

    - uses: ConorMacBride/install-package@v1
      name: Install APT packages
      with:
        apt: nodejs npm cmake gcc gcc-arm-none-eabi cppcheck clang-format libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Create changelog & bump version
      if: ${{ inputs.release }}
      run: npm run beachball:bump

    - name: Run build
      id: run-build
      run: node build --rebuild --target rp2xxx --release

    - name: Merge version bump
      if: ${{ inputs.release }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -a -m "Version bump to v${{ steps.run-build.outputs.PACKAGE_VERSION }}"
        git push

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/pico-sdk-js-*.*

  release:
    if: ${{ inputs.release }}
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          CHANGELOG.md
        sparse-checkout-cone-mode: false

    - name: Download artifacts from build job
      uses: actions/download-artifact@v4
      with:
        name: build
        path: artifact
          
    - name: Create Release
      id: release-step
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{needs.build.outputs.PACKAGE_VERSION}}
        name: ${{needs.build.outputs.PACKAGE_NAME}} v${{needs.build.outputs.PACKAGE_VERSION}}
        body_path: CHANGELOG.md
        draft: false
        prerelease: true
        fail_on_unmatched_files: true
        files: |
          artifact/${{ needs.build.outputs.PRODUCT_NAME }}.uf2
          artifact/${{ needs.build.outputs.PRODUCT_NAME }}.elf
          artifact/${{ needs.build.outputs.PRODUCT_NAME }}.elf.map
          artifact/${{ needs.build.outputs.PRODUCT_NAME }}.bin

    - name: Append Build Log
      run: |
        echo "### Release ${{ steps.release-step.outputs.id }} published" >> $GITHUB_STEP_SUMMARY
        echo "[Release ${{needs.build.outputs.PACKAGE_NAME}} v${{needs.build.outputs.PACKAGE_VERSION}}](${{ steps.release-step.outputs.url }})" >> $GITHUB_STEP_SUMMARY
